- hosts: localhost
  connection: local

  #vars_files:
  #  - config.yml

  roles:
    - role: xxx.xxx
      when: variable

  tasks:
    - import_tasks: tasks/core_app.yml

#    - name: Reboot
#      command: reboot
#      become: yes