---

- name: Install Core Apps
  win_chocolatey:
    name:
    - 7zip —y # OK
    - googlechrome —y # OK
    - dropbox —y # OK
    - firefox —y # OK
    - foxitreader —y # OK
    - git —y # OK
    - notepadplusplus.install —y # OK
    - onenote —y # OK
    - pycharm-community —y # OK
#   - python2 # OK - Already installed for Ansible
    - skype —y # OK
    - skypeforbusiness —y # OK
    - slack —y # OK
    - spotify —y # OK
    - sublimetext3 —y # OK
    - sysinternals —y # OK
    - microsoft-teams —y # OK
    - vlc —y # OK
    - vscode —y # OK
    - winscp —y # OK
    state: present

#- name: Install Linux Subsystem
#          - Linux subsystem (Debian)

#- name: Install Outlook
#      - Outlook

#- name: Install cfn-lint
#      - cfn-lint # CloudFormation Lint